# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Brett/source/repos/ECE449/project_cpu/project_cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/Brett/source/repos/ECE449/project_cpu/project_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Brett/source/repos/ECE449/project_cpu/project_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/Brett/source/repos/ECE449/mem code/rom_test.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/testB2.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/testA.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/testB2_V2.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/TestL.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/testB2_V3.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/load_hazard_test.mem}
  {C:/Users/Brett/source/repos/ECE449/mem code/boot_loader.mem}
}
read_vhdl -library xil_defaultlib {
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/RF8_16.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/cpu_types.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/adder.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/execute/alu.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/bit_to_ascii.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/memory/branch_unit.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/console.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/controller.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/memory/rom.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/memory/ram.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/memory/mem_manager.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/fetch/program_counter.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/fetch/fetch_register.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/hazard_detect_unit.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/decoder.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/imm_concat.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/sign_extend.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/decode/decode_register.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/execute/execute_register.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/memory/memory_register.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/datapath.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/led_display.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/nibble_to_ascii.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/video_timing.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/debug_display/word_to_ascii.vhd
  C:/Users/Brett/source/repos/ECE449/sub_modules/cpu_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Brett/source/repos/ECE449/constraints/CPU16_BASYS3.xdc
set_property used_in_implementation false [get_files C:/Users/Brett/source/repos/ECE449/constraints/CPU16_BASYS3.xdc]


synth_design -top cpu_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb"
